### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by 0xAurelou** [onlydustxyz/kaaper#44]
Hello,

I wanted to generate some docs for my project but I have some trouble, I followed the README and have a big issue :frowning_face: 
As you can see on the attached screenshot I have a ``module not found error``

![image](https://user-images.githubusercontent.com/63618058/205843523-0da30b2b-923d-430c-a289-91d1638ab82f.png)

Do you know how to fix it ?

Thanks

**Comment by msaug** [comment]
@AnthonyBuisset this is because the published version of Kaaper is not up to date with the latest commits, I don't have the writing rights to create a `0.1.5` tag and push to trigger publishing

**Comment by AnthonyBuisset** [comment]
Done => https://www.npmjs.com/package/@onlydust/kaaper

**Comment by msaug** [comment]
@AnthonyBuisset can you please close this issue?
