### ISSUE TITLE
vscode extention

### ISSUE THREAD

**Issue by AnthonyBuisset** [onlydustxyz/kaaper#5]
### Details
As a developer I want my doc comments to be highlighted and auto-completed so that it increases my productivity

Either an existing extention is updated or a new dedicated one is created with the following features:
- syntax highlighting
- auto-completion of the comments
- consistency checks with the code

_Note: This issue can be splitted if needed_ 

### Acceptance Criteria
- documentation comments are highlighted following the standard delivered in #4
- auto-completion works for doc comments
- in-line red squiggles with a tooltip is being displayed if comments do not match the code

**Comment by internnos** [comment]
```
- documentation comments are highlighted following the standard delivered in https://github.com/onlydustxyz/kaaper/issues/4
- auto-completion works for doc comments
- in-line red squiggles with a tooltip is being displayed if comments do not match the code
```

i propose the in-line red squiggles if the comments does not match the code to close this issue.

because i think autocompletion already work with other extension such as `TabNine` or `copilot`

what do you think @AnthonyBuisset ?

thank you

**Comment by AnthonyBuisset** [comment]
Good enough for me !

**Comment by internnos** [comment]
> Good enough for me !

gotcha!

**Comment by internnos** [comment]
this is taking longer than expected

it turns out that i have to refactor the parser to return character index so `in-line red squiggles` can be displayed

all of the scopes expect namespace were refactored

currently doing the namespace

**Comment by internnos** [comment]
right now, because there are multiple entrypoints (cli vs vscode extension), things are getting a little bit out of hand

I think it would be much better to create 3 different repositories

`kaaper-lib`

where kaaper-lib will be submoduled in the repository below

`kaaper-cli`
`kaaper-vsode`

else, we have to deal with multiple entrypoints in a repository. what do you think @AnthonyBuisset ?

**Comment by AnthonyBuisset** [comment]
@internnos 
If all your entry points are in the same language, I have no issue with keeping a single repository with 3 folders: vscode-extension, cli, core

you can also have another folder, like `model` to store the data model that will be used by all other modules

splitting repositories can be a solution if the modules have a different lifetime, but it can be done later

**Comment by internnos** [comment]
aah make sense

will try to do it

ill let you know if i have some bottlenecks regarding different entrypoints

last time i tried, i haven't really succeed

**Comment by internnos** [comment]
i still not be able to put multiple entrypoints in a repository

the thing is, it works if `cli` and `vscode-extension` is in different repository

to give a little context, in order for `vscode-extension` to work, there are `client` and `server` repository and have structure as seen below

.
├── client // Language Client
│   ├── src
│   │   ├── test // End to End tests for Language Client / Server
│   │   └── extension.ts // Language Client entry point
├── package.json // The extension manifest.
└── server // Language Server
    └── src
        └── server.ts // Language Server entry point
        └── lib // kaaper core library

this works perfectly

however when I added `cli` entrypoint, it become like this

├── cli // entry point for CLI commands
├── client // Language Client
│   ├── src
│   │   ├── test // End to End tests for Language Client / Server
│   │   └── extension.ts // Language Client entry point
├── package.json // The extension manifest.
└── server // Language Server
    └── src
        └── server.ts // Language Server entry point
        └── lib // kaaper core library
        
 but i can't get `cli` to acces `server/src/lib` which serves as the core library

are there anything i should change to get everything working in a repo? or this should be put in separate repository as our prior discussion

thank you

cc @AnthonyBuisset

**Comment by AnthonyBuisset** [comment]
Would it be possible to have a vscode-extension folder with both client and server ?
And publish subdirectories as npm packages ?
I am not an expert in node and packages...
I let you investigate on the web what are the best practices or if you can find examples.

Then we will make a decision to split if needed

**Comment by internnos** [comment]
> Would it be possible to have a vscode-extension folder with both client and server ?
do you mean the structure would be like this?

├── vscode-extension
|    ├── client // Language Client
|    │   ├── src
|    │   │   ├── test // End to End tests for Language Client / Server
|    │   │   └── extension.ts // Language Client entry point
|    ├── package.json // The extension manifest.
|    └── server // Language Server
|        └── src
|            └── lib // kaaper-core
|            └── server.ts // Language Server entry point
├── cli
└── src
    └── lib // kaaper-core
    └── index.ts // CLI entry point
 
 actually this might work, but the kaaper-core is independent between `vscode-extension` and `cli`. if we want to point out to the same `kaaper-core` it would be painful to manage.

so hackish way to do it is to just copy and past the kaaper-core but both have independent entrypoints rather than trying to make use of one `kaaper-core`

**Comment by AnthonyBuisset** [comment]
I see, so you want to have a kaaper-core submodule that is used as a dependency on both vscode-extension and the cli.
Referencing this dependency pointing to the root level would not work ?

```
|- lib
|.   |- core
|
|-vscode-extension
|
|- cli
|.   |- src/index.js (import ../lib/core)
```

**Comment by internnos** [comment]
> I see, so you want to have a kaaper-core submodule that is used as a dependency on both vscode-extension and the cli. Referencing this dependency pointing to the root level would not work ?
> 
> ```
> |- lib
> |.   |- core
> |
> |-vscode-extension
> |
> |- cli
> |.   |- src/index.js (import ../lib/core)
> ```

i've tried this but currently not working

will try again later and see if it works with certain hacks!

**Comment by internnos** [comment]
after trying out different things, i think this is the best i can come up with for now

<img width="263" alt="Screen Shot 2022-08-04 at 9 35 18 pm" src="https://user-images.githubusercontent.com/26416205/182947596-4537939e-585c-4248-9b04-56666a42dd46.png">

each entrypoint have to have its dependencies, so i don't think it would be possible to make a single `yarn.lock`, `package.json` and etc or maybe we can open this issue to explore this.

if this is okay, i will make proper docs, combining cli and vscode extension.

and also, to publish the vscode extension, i think should be out of scope according to the acceptance criteria so i'd open the issue to track this instead

what do you think @AnthonyBuisset?

thank you

**Comment by AnthonyBuisset** [comment]
Ok let's start with this. Please open an issue to track the split and deployment

**Comment by internnos** [comment]
gotcha!
